name: Rust
on: [push]

jobs:
  windows:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          toolchain: nightly-${{ matrix.config.arch }}-pc-windows-msvc
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release

      - run: Rename-Item -Path "target\release\classicube_mention_flash_plugin.dll" -NewName "classicube_mention_flash_windows_${{ matrix.config.arch }}.dll"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/classicube_mention_flash_windows_${{ matrix.config.arch }}.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
